### ISSUE TITLE
Lot of new failures today

### ISSUE THREAD

**Issue by quicklisp** [mnasoft/math#1]
All seem to be package related. Log here: http://report.quicklisp.org/2020-09-10/failure-report/math.html

**Comment by quicklisp** [comment]
Any word on this?

**Comment by quicklisp** [comment]
I won't be able to keep the project in Quicklisp if there's no fix for the broken systems.

**Comment by mnasoft** [comment]
Recheck math project please. Last update of project is 2020-10-17.

**Comment by mnasoft** [comment]
Recheck math project please. Last update of project is 2020-10-17.

**Comment by quicklisp** [comment]
It looks good to me, thanks for the update!
