### ISSUE TITLE
find-method is not supposed to accept classnames. 

### ISSUE THREAD

**Issue by Yehouda** [mnasoft/math#10]
https://github.com/mnasoft/math/blob/6a0f6dea05004551a94c3cb66098f8f41ef76461/src/matr/matr-doc.lisp#L14
https://github.com/mnasoft/math/blob/6a0f6dea05004551a94c3cb66098f8f41ef76461/src/matr/matr-doc.lisp#L19

[find-methd](https://www.lispworks.com/documentation/lw70/CLHS/Body/f_find_m.htm) is documented to take a list of [parameter specializers](https://www.lispworks.com/documentation/lw70/CLHS/Body/26_glo_p.htm#parameter_specializer), and [parameter specializers](https://www.lispworks.com/documentation/lw70/CLHS/Body/26_glo_p.htm#parameter_specializer) are supposed to be either a class or a list of (eql object). To allow also class names, it has to be [parameter specializer names](https://www.lispworks.com/documentation/lw70/CLHS/Body/26_glo_p.htm#parameter_specializer_name). 

The standard may be daft, but currently any standard-compliant implemenation errors on these two lines. LispWorks does. 

Changing these lines to:
```
 (find-method #'MATH/MATR:TRANSPOSE NIL (list (find-class 'cons)))

 (find-method #'MATH/MATR:ROWS NIL (list (find-class 'array)))
```
prevents the error.

**Comment by mnasoft** [comment]
Thank you.
Corresponding changes have been made to the MNAS-PACKAGE system.
