### ISSUE TITLE
ASDF description is not in English

### ISSUE THREAD

**Issue by phoe** [mnasoft/math#2]
https://github.com/mnasoft/math/blob/2d8753e430fdde29f459f02a5dbf7680b218a97a/math.asd#L4-L11

Since this project is in Quicklisp now, would you mind changing the ASDF description to English?

**Comment by mnasoft** [comment]
"Math is a math library, implementing some algorithms:
@begin(list)
 @item(linear algebra;)
 @item(operations with matrices;)
 @item(statistical functions;)
 @item(linear and bilinear interpolation;)
 @item(finding approximating polynomials, implemented in Common
       Lisp.)
@end(list)
"
