### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [mnasoft/math#3]
Building with SBCL 2.0.10.118-cdfa399c4 / ASDF 3.3.1 for quicklisp dist creation.

Commit id 542c149c66037fa0efa68c15679ef1b5b2e11bc9

*math/appr* fails to build with the following error:

```
Unhandled PACKAGE-DOES-NOT-EXIST in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001720103}>: The name "MATH/CORE" does not designate any package.

```

*math/arr-matr* fails to build with the following error:

```
Unhandled PACKAGE-DOES-NOT-EXIST in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001720103}>: The name "MATH/CORE" does not designate any package.

```

*math/coord* fails to build with the following error:

```
Unhandled PACKAGE-DOES-NOT-EXIST in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001720103}>: The name "MATH/CORE" does not designate any package.

```

*math/docs* fails to build with the following error:

```
Unhandled ASDF/FIND-COMPONENT:MISSING-DEPENDENCY in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001720103}>: Component "mnas-package" not found, required by #<SYSTEM "math/docs">

```

*math/ls-gauss* fails to build with the following error:

```
Unhandled PACKAGE-DOES-NOT-EXIST in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001720103}>: The name "MATH/CORE" does not designate any package.

```

*math/ls-rotation* fails to build with the following error:

```
Unhandled PACKAGE-DOES-NOT-EXIST in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001720103}>: The name "MATH/ARR-MATR" does not designate any package.

```

[Full log here](http://report.quicklisp.org/2020-11-26/failure-report/math.html)

**Comment by mnasoft** [comment]
Recheck it please.
But mnas-package and it's dependencies are not yet in quicklisp.

**Comment by quicklisp** [comment]
These are still an issue.

**Comment by mnasoft** [comment]
Recheck it please.
   b292e6b..607ae3a  master -> master
mnas-package removed from dependencies.

**Comment by quicklisp** [comment]
The only remaining error I get is with math/ls-rotation: MATH/ARR-MATR does not designate any package.

**Comment by mnasoft** [comment]
Recheck it please.
607ae3a..0ab85a3  master -> master
math/arr-matr remove from dependencies for math/ls-rotation.
