### ISSUE TITLE
Symbol clashes between core and arr-matr

### ISSUE THREAD

**Issue by Yehouda** [mnasoft/math#5]
Both math/core and math-arr/matr exports **anti-diagnonal**, so if both packages are used they clash. That seems to be true for all the symbols in this group.  How is this supposed to work? 
**x-o**  uses them both, and hence gets an error.

https://github.com/mnasoft/math/blob/396b22c9192fde65e90070cf28ed7fb92e18845f/src/core/core.lisp#L29
https://github.com/mnasoft/math/blob/396b22c9192fde65e90070cf28ed7fb92e18845f/src/arr-matr/arr-matr.lisp#L32

https://github.com/mnasoft/math/blob/396b22c9192fde65e90070cf28ed7fb92e18845f/src/x-o/x-o.lisp#L4

**Comment by mnasoft** [comment]
(:use #:cl #:math/core #:math/arr-matr) ->(:use #:cl #:math/matr)
