### ISSUE TITLE
Refernces to sb-mop broken on othe rimplementation. Should use closer-mop instead

### ISSUE THREAD

**Issue by Yehouda** [mnasoft/math#7]
https://github.com/mnasoft/math/blob/e757b68deae17ce4643e6d89a4b4b883b10b0437/src/matr/matr-doc.lisp#L11

This reference to sb-mop means that this code doesn't veen compile on implementation apart from sbcl.
Changing it to use closer-mop instead will make it compatible. 
https://github.com/pcostanza/closer-mop

**Comment by mnasoft** [comment]
sb-mop replaced with closer-mop
